# Site settings
title: SLATE
url: https://slatepool.io
description: "A new Cardano stake pool"

# Build settings
markdown: kramdown
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-target-blank

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#e22f70'
  links-hover: '#aa2354'

# #e22f70 #ff2a2a

# Footer settings
footer: SLATE Operators

exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE

sass:
  sass_dir: _sass
  style: :compressed

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap
